# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/user/Documents/PV/Proyecto1-main/Proy1_SEP/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Sequence_Memory_0_1/design_1_Sequence_Memory_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Sequence_Memory_0_1 || ORIG_REF_NAME==design_1_Sequence_Memory_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_StateMachine_P1_0_0/design_1_StateMachine_P1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_StateMachine_P1_0_0 || ORIG_REF_NAME==design_1_StateMachine_P1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Btn_Debouncer_0_0/design_1_Btn_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Btn_Debouncer_0_0 || ORIG_REF_NAME==design_1_Btn_Debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MUX_VIO_0_1/design_1_MUX_VIO_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MUX_VIO_0_1 || ORIG_REF_NAME==design_1_MUX_VIO_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_simon_v3_0_0/design_1_simon_v3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_simon_v3_0_0 || ORIG_REF_NAME==design_1_simon_v3_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_traffic_gen_0_0/design_1_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_traffic_gen_0_0 || ORIG_REF_NAME==design_1_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RGB_Driver_0_0/design_1_RGB_Driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RGB_Driver_0_0 || ORIG_REF_NAME==design_1_RGB_Driver_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_juegoswitches_0_0/design_1_juegoswitches_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_juegoswitches_0_0 || ORIG_REF_NAME==design_1_juegoswitches_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Mult2_inputs_0_0/design_1_Mult2_inputs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Mult2_inputs_0_0 || ORIG_REF_NAME==design_1_Mult2_inputs_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_100M_1/design_1_rst_clk_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_100M_1 || ORIG_REF_NAME==design_1_rst_clk_100M_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
