# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/sbast/Desktop/PROYECTO01_SEP/Proyecto1/Proy1_SEP/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Sequence_Memory_0_1/design_1_Sequence_Memory_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Sequence_Memory_0_1 || ORIG_REF_NAME==design_1_Sequence_Memory_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RNG_0_0/design_1_RNG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RNG_0_0 || ORIG_REF_NAME==design_1_RNG_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_StateMachine_P1_0_0/design_1_StateMachine_P1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_StateMachine_P1_0_0 || ORIG_REF_NAME==design_1_StateMachine_P1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Btn_Debouncer_0_0/design_1_Btn_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Btn_Debouncer_0_0 || ORIG_REF_NAME==design_1_Btn_Debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Mult2_0_0/design_1_Mult2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Mult2_0_0 || ORIG_REF_NAME==design_1_Mult2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_simon_says_0_0/design_1_simon_says_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_simon_says_0_0 || ORIG_REF_NAME==design_1_simon_says_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
