# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/sbast/Desktop/PROYECTO01_SEP/P1_SEBA/Zybo-Z7-Master.xdc

# Block Designs: bd/simon_says_debug/simon_says_debug.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simon_says_debug || ORIG_REF_NAME==simon_says_debug} -quiet] -quiet

# IP: bd/simon_says_debug/ip/simon_says_debug_vio_0_0/simon_says_debug_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simon_says_debug_vio_0_0 || ORIG_REF_NAME==simon_says_debug_vio_0_0} -quiet] -quiet

# IP: bd/simon_says_debug/ip/simon_says_debug_Btn_Debouncer_0_0/simon_says_debug_Btn_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simon_says_debug_Btn_Debouncer_0_0 || ORIG_REF_NAME==simon_says_debug_Btn_Debouncer_0_0} -quiet] -quiet

# IP: bd/simon_says_debug/ip/simon_says_debug_ila_0_0/simon_says_debug_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simon_says_debug_ila_0_0 || ORIG_REF_NAME==simon_says_debug_ila_0_0} -quiet] -quiet

# IP: bd/simon_says_debug/ip/simon_says_debug_simon_v3_0_0/simon_says_debug_simon_v3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simon_says_debug_simon_v3_0_0 || ORIG_REF_NAME==simon_says_debug_simon_v3_0_0} -quiet] -quiet

# IP: bd/simon_says_debug/ip/simon_says_debug_Simple_RAM_0_1/simon_says_debug_Simple_RAM_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==simon_says_debug_Simple_RAM_0_1 || ORIG_REF_NAME==simon_says_debug_Simple_RAM_0_1} -quiet] -quiet

# XDC: bd/simon_says_debug/simon_says_debug_ooc.xdc
